name: pytesting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install
        poetry add pytest pytest-cov pytest-mock pytest-coverage
    - name: Test with pytest
      run: |
        poetry run pytest --cov
    - name: Creating coverage folder
      run: |
        mkdir -p coverage
    - name: Coverage Bagdge
      uses: tj-actions/coverage-badge-py@v1.8
      with:
        output: coverage/coverage.svg
    - name: Publish coverage report to coverage-badge branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: coverage-badge
        folder: coverage